---
title: "clean_mouse"
format: html
editor: visual
---

## Quarto

This document cleanes the mouse data

```{r}
library(dplyr)
library(tidyr)
library(tidyverse)
```

```{r}
mouse_data <- read_tsv(file = "../data/01_dat_load_mouse.tsv.gz")
```


```{r}
# Convert to long format
mouse_data_long <- mouse_data_backup %>%
  pivot_longer(
    cols = -c(gene_id, symbol), # Exclude gene_id and symbol
    names_to = "treatment_replicate",
    values_to = "value"
  )

# Separate the treatment and replicate information
mouse_data_separated <- mouse_data_long %>%
  separate(
    col = treatment_replicate,
    into = c("treatment", "replicate"),
    sep = "\\." # The separator is a period, escaped because it's a special character in regex
  )

# View the result
head(mouse_data_separated)

```

```{r}
mouse_data_combined <- mouse_data_separated %>%
  mutate(gene_id_symbol = paste(gene_id, symbol, sep = "_")) |>
  select(-gene_id, -symbol)

```

```{r}
mouse_wide<-pivot_wider(mouse_data_combined, names_from = gene_id_symbol)
```

```{r}
data_dir <- 
file_name <- 
write_tsv(x = mouse_wide, file = str_c("../data/02_dat_clean_mouse", ".tsv.gz"))
```

